use_frameworks!

target 'NEIApplicationConfig_Example' do
  pod 'NEIApplicationConfig', :path => '../'

  target 'NEIApplicationConfig_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  end
end
